"""Core event and state models for the backtesting engine.

The engine is event-driven: bars -> signals -> orders -> fills. Every
model is an immutable, stdlib-only dataclass. Timestamps are UTC.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from math import isfinite


class SignalAction(Enum):
    LONG = "long"    # target a long position (sized by the position sizer)
    SHORT = "short"  # target a short position
    EXIT = "exit"    # flatten the position


class OrderAction(Enum):
    BUY = "buy"
    SELL = "sell"


class OrderType(Enum):
    MARKET = "market"
    LIMIT = "limit"


def ensure_utc(value: datetime) -> datetime:
    if not isinstance(value, datetime):
        raise TypeError(f"expected datetime, got {type(value).__name__}")
    if value.tzinfo is None:
        return value.replace(tzinfo=timezone.utc)
    return value.astimezone(timezone.utc)


def _finite(name: str, value: float) -> float:
    if not isinstance(value, (int, float)) or not isfinite(value):
        raise ValueError(f"{name} must be a finite number, got {value!r}")
    return float(value)


@dataclass(frozen=True, slots=True)
class Bar:
    """One normalized OHLCV bar. See ``data.normalize_bar`` for adapters."""

    symbol: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float = 0.0

    def __post_init__(self) -> None:
        symbol = self.symbol.strip().upper()
        if not symbol:
            raise ValueError("symbol must be a non-empty string")
        object.__setattr__(self, "symbol", symbol)
        object.__setattr__(self, "timestamp", ensure_utc(self.timestamp))
        for name in ("open", "high", "low", "close"):
            _finite(name, getattr(self, name))
        if not (self.low <= self.open <= self.high and self.low <= self.close <= self.high):
            raise ValueError("bar violates low <= open/close <= high")
        if not isfinite(self.volume) or self.volume < 0:
            raise ValueError(f"volume must be non-negative, got {self.volume!r}")


@dataclass(frozen=True, slots=True)
class Signal:
    """A strategy's intent for one symbol at one timestamp."""

    symbol: str
    timestamp: datetime
    action: SignalAction
    strength: float = 1.0          # 0..1 conviction; sizers may scale by it
    limit_price: float | None = None  # set for limit entry/exit

    def __post_init__(self) -> None:
        symbol = self.symbol.strip().upper()
        if not symbol:
            raise ValueError("symbol must be a non-empty string")
        object.__setattr__(self, "symbol", symbol)
        object.__setattr__(self, "timestamp", ensure_utc(self.timestamp))
        if not 0.0 <= self.strength <= 1.0:
            raise ValueError(f"strength must be 0..1, got {self.strength!r}")


@dataclass(frozen=True, slots=True)
class Order:
    """An order generated by the portfolio from a signal.

    ``is_entry`` tells execution which slippage knob to use: ``True``
    when the order opens or increases the absolute position, ``False``
    when it closes or reduces it. The portfolio sets it in
    ``on_signal``; for reversals (one order both closes and opens) the
    *dominant* leg decides -- ties classify as entry. This is a
    documented approximation: a reversal really pays both knobs.
    """

    symbol: str
    timestamp: datetime
    action: OrderAction
    quantity: float
    order_type: OrderType = OrderType.MARKET
    limit_price: float | None = None
    is_entry: bool = True

    def __post_init__(self) -> None:
        symbol = self.symbol.strip().upper()
        if not symbol:
            raise ValueError("symbol must be a non-empty string")
        object.__setattr__(self, "symbol", symbol)
        object.__setattr__(self, "timestamp", ensure_utc(self.timestamp))
        if not isfinite(self.quantity) or self.quantity <= 0:
            raise ValueError(f"quantity must be positive, got {self.quantity!r}")
        if self.order_type is OrderType.LIMIT and self.limit_price is None:
            raise ValueError("limit orders require a limit_price")
        if not isinstance(self.is_entry, bool):
            raise ValueError(f"is_entry must be a bool, got {self.is_entry!r}")


@dataclass(frozen=True, slots=True)
class Fill:
    """A simulated execution of an order.

    ``price`` is the fill price *including* adverse slippage (buys lift,
    sells hit) -- slippage is a price effect, so it lives in the price.
    ``slippage`` records that price effect in dollars for the
    decomposition; ``spread_cost`` is the half-spread crossing cost,
    charged to cash separately (never double-counted in the price).
    ``total_cost`` is the full priced decomposition of the fill.
    """

    symbol: str
    timestamp: datetime
    action: OrderAction
    quantity: float
    price: float
    commission: float = 0.0
    slippage: float = 0.0
    spread_cost: float = 0.0

    def __post_init__(self) -> None:
        object.__setattr__(self, "symbol", self.symbol.strip().upper())
        object.__setattr__(self, "timestamp", ensure_utc(self.timestamp))
        _finite("price", self.price)
        for name in ("commission", "slippage", "spread_cost"):
            value = getattr(self, name)
            if value < 0 or not isfinite(value):
                raise ValueError(f"{name} must be non-negative, got {value!r}")

    @property
    def signed_quantity(self) -> float:
        return self.quantity if self.action is OrderAction.BUY else -self.quantity

    @property
    def total_cost(self) -> float:
        """Full priced decomposition: commission + slippage + spread."""
        return self.commission + self.slippage + self.spread_cost


@dataclass(frozen=True, slots=True)
class Trade:
    """One closed round-trip (FIFO lot matched)."""

    symbol: str
    entry_time: datetime
    exit_time: datetime
    quantity: float
    entry_price: float
    exit_price: float
    pnl: float
    commission: float = 0.0

    @property
    def return_pct(self) -> float:
        notional = self.entry_price * self.quantity
        return self.pnl / notional if notional else 0.0


@dataclass(frozen=True, slots=True)
class EquityPoint:
    timestamp: datetime
    equity: float
    cash: float
